ARG VERSION=2.3.3
FROM docker.io/library/alpine:3.20 AS down
ARG VERSION
RUN apk add --no-cache curl ca-certificates unzip \
	&& curl -fsSL "https://github.com/projectdiscovery/naabu/releases/download/v${VERSION}/naabu_${VERSION}_linux_amd64.zip" -o /tmp/t.zip \
	&& unzip -j /tmp/t.zip naabu -d /usr/local/bin \
	&& chmod +x /usr/local/bin/naabu
FROM docker.io/library/alpine:3.20
RUN apk add --no-cache ca-certificates libpcap \
	&& rm -rf /var/cache/apk/*
COPY --from=down /usr/local/bin/naabu /usr/local/bin/naabu
ENTRYPOINT ["naabu"]
