import assert from 'node:assert/strict';
import {
	buildEngagementPdfDocument,
	cleanPdfStep,
	clipPdfNote,
	dedupePdfFindings,
	formatPdfChatTitle,
	renderPdfLite,
	restorePdfAddresses,
	stripMarkdownTokens,
} from './pdf-lite.ts';

assert.equal(formatPdfChatTitle('Juice Shop SSRF lab', 'abc'), 'Juice Shop SSRF lab');
assert.equal(formatPdfChatTitle('', 'abcdefghijklm'), 'abcdefgh');
assert.equal(formatPdfChatTitle('none', ''), 'Unassigned');
assert.equal(formatPdfChatTitle('Chat none', ''), 'Unassigned');
assert.equal(formatPdfChatTitle('Chat', 'thread-99'), 'thread-99');
assert.equal(formatPdfChatTitle('', ''), 'Unassigned');
assert.equal(cleanPdfStep('1. 1. Tested SSRF via image URL'), 'Tested SSRF via image URL');
assert.equal(stripMarkdownTokens('## Summary **bold** | Severity |'), 'Summary bold Severity');
assert.equal(restorePdfAddresses('http://[IP_ADDRESS]:3000/profile'), 'http://127.0.0.1:3000/profile');
assert.equal(restorePdfAddresses('[IP_ADDRESS]'), '127.0.0.1');
assert.match(clipPdfNote('Is SSRF possible when the profile image URL is attacker-controlled on this instance?', 48), /\.\.\.$/);
assert.doesNotMatch(clipPdfNote('Is SSRF possible when the profile image URL is attacker-controlled on this instance?', 48), /\?$/);

const ssrf = {
	title: '### 1. [HIGH] Server-side request forgery',
	severity: 'high',
	vulnClass: 'ssrf',
	status: 'confirmed' as const,
	target: 'http://[IP_ADDRESS]:3000/profile/image',
	description: 'The profile image fetch followed an operator-supplied URL.',
	steps: ['1. 1. Tested SSRF via the profile image endpoint'],
	evidence: '```\nGET /profile/image status 500\nHost header reflected\n```',
	request: { method: 'GET', url: 'http://[IP_ADDRESS]:3000/profile/image', status: 500 },
	impact: 'Internal hosts may be reachable through the image fetcher.',
	remediation: 'Allowlist destinations for server-side fetches.',
};

const document = buildEngagementPdfDocument(
	[
		ssrf,
		{ ...ssrf, evidence: 'GET /profile/image status 500' },
		{ ...ssrf, description: 'Same SSRF story recorded again.' },
		{
			title: 'Open redirect on /redirect',
			severity: 'low',
			vulnClass: 'other',
			status: 'hypothesis',
			target: 'http://127.0.0.1:3000/redirect',
			description: 'Is the redirect parameter honored without an allowlist check on this Juice Shop instance?',
		},
	],
	{
		title: 'Engagement report',
		chatTitle: 'Chat none',
		sessionId: '',
		reportId: 'rpt-mt1a0sefxcuv',
		target: 'http://[IP_ADDRESS]:3000',
		generatedAt: new Date('2026-08-20T12:00:00'),
	},
);

assert.equal(document.cover.chatTitle, 'Unassigned');
assert.equal(document.cover.kicker, 'Authorized engagement report');
assert.equal(document.cover.target, 'http://127.0.0.1:3000');
assert.match(document.cover.date, /20 August 2026, 12:00/);
assert.equal(document.blocks.filter((block) => block.type === 'finding').length, 1);
assert.equal(document.blocks.some((block) => block.type === 'table'), true);
assert.equal(document.blocks.some((block) => block.type === 'figures'), true);

const hypoList = document.blocks.find((block) => block.type === 'list');
assert.equal(hypoList?.type, 'list');
if (hypoList?.type === 'list') {
	assert.equal(hypoList.items.length, 1);
	assert.equal(hypoList.items[0].title, 'Open redirect on /redirect');
	assert.match(hypoList.items[0].note || '', /allowlist check/);
}

assert.equal(dedupePdfFindings([ssrf, ssrf, ssrf]).length, 1);

const titled = buildEngagementPdfDocument([], {
	reportId: 'rpt-named',
	chatTitle: 'OWASP Juice Shop',
	sessionId: 'deadbeef-thread',
	target: '[IP_ADDRESS]',
});
assert.equal(titled.cover.chatTitle, 'OWASP Juice Shop');
assert.equal(titled.cover.target, '127.0.0.1');

const bytes = renderPdfLite({
	title: 'Engagement report',
	watermark: 'HAWALDAR · AUTHORIZED ENGAGEMENT · 2026-08-20 · Chat none',
	footer: 'Generated by Hawaldar. Not for unaffiliated redistribution as original work.',
	document,
});

assert.ok(bytes.byteLength > 8);
assert.equal(Buffer.from(bytes.subarray(0, 4)).toString('latin1'), '%PDF');
const asText = Buffer.from(bytes).toString('latin1');

assert.match(asText, /HAWALDAR/);
assert.match(asText, /Authorized engagement report/);
assert.match(asText, /Unassigned/);
assert.match(asText, /rpt-mt1a0sefxcuv/);
assert.match(asText, /http:\/\/127\.0\.0\.1:3000/);
assert.match(asText, /Not for unaffiliated redistribution/);
assert.match(asText, /\/F2 18 Tf/);
assert.match(asText, /\/F2 14 Tf/);
assert.match(asText, /\/F1 10 Tf/);
assert.match(asText, /\/F3 8 Tf/);
assert.match(asText, /\/F2 22 Tf/);
assert.match(asText, /HIGH/);
assert.match(asText, /Evidence/);
assert.match(asText, /Severity/);
assert.match(asText, /Generated/);
assert.match(asText, /1\. Server-side request forgery/);
assert.match(asText, /1 \/ \d+/);

assert.doesNotMatch(asText, /## /);
assert.doesNotMatch(asText, /### /);
assert.doesNotMatch(asText, /\*\*bold\*\*/);
assert.doesNotMatch(asText, /\| Severity \| Count \|/);
assert.doesNotMatch(asText, /Chat none/);
assert.doesNotMatch(asText, /1\. 1\./);
assert.doesNotMatch(asText, /\[IP_ADDRESS\]/);
assert.doesNotMatch(asText, /HAWALDAR · AUTHORIZED ENGAGEMENT/);
assert.equal((asText.match(/Server-side request forgery/g) || []).length, 1);

const mdBytes = renderPdfLite({
	title: 'Markdown fallback',
	watermark: 'HAWALDAR',
	footer: 'Generated by Hawaldar. Not for unaffiliated redistribution as original work.',
	body: [
		'# Finding',
		'',
		'## Summary',
		'',
		'| Severity | Count |',
		'| --- | --- |',
		'| HIGH | 1 |',
		'',
		'**Reproduction (PoC):**',
		'',
		'1. 1. Tested SSRF via image URL',
		'',
		'**Evidence:**',
		'',
		'‘‘‘',
		'GET /profile',
		'‘‘‘',
		'',
		'Retest PoC no longer reproduces.',
	].join('\n'),
});
const mdText = Buffer.from(mdBytes).toString('latin1');
assert.match(mdText, /\/F2 14 Tf/);
assert.match(mdText, /\/F1 10 Tf/);
assert.match(mdText, /Finding/);
assert.match(mdText, /Summary/);
assert.match(mdText, /GET \/profile/);
assert.doesNotMatch(mdText, /## Summary/);
assert.doesNotMatch(mdText, /\| Severity \| Count \|/);
assert.doesNotMatch(mdText, /\*\*Evidence:\*\*/);
assert.doesNotMatch(mdText, /1\. 1\./);

const wrapDoc = buildEngagementPdfDocument(
	[
		{
			title: 'Hypothesis that must wrap rather than truncate',
			severity: 'info',
			vulnClass: 'ssrf',
			status: 'hypothesis',
			target: 'http://127.0.0.1:3000/profile/image?url=http://example.invalid/long',
			description: 'Is server-side request forgery possible when the profile image URL is attacker-controlled on this authorized Juice Shop instance?',
		},
	],
	{ reportId: 'rpt-wrap', chatTitle: 'none', sessionId: 'abcd1234efgh' },
);
const wrapText = Buffer.from(renderPdfLite({ document: wrapDoc, footer: 'Generated by Hawaldar.' })).toString('latin1');
assert.match(wrapText, /abcd1234/);
assert.match(wrapText, /Hypothesis that must wrap/);
assert.match(wrapText, /attacker-controlled/);
assert.doesNotMatch(wrapText, /Chat none/);
assert.doesNotMatch(wrapText, /\[IP_ADDRESS\]/);

console.log('pdf-lite ok');
