/** Lightweight catalog copy for the settings UI (mirrors core TOOL_CATALOG ids). */
const min = (id: string) => `localhost/hawaldar/${id}:min`;

export const TOOL_CATALOG = [
	{ id: 'discover-hosts', title: 'Discover hosts', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'quick-scan', title: 'Quick scan', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'scan-ports', title: 'Scan ports', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'detect-services', title: 'Detect services', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'scan-top-ports', title: 'Scan top ports', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'scan-local-ports', title: 'Scan local ports', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'scan-port-range', title: 'Scan port range', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'probe-http-ports', title: 'Probe HTTP ports', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'reverse-dns', title: 'Reverse DNS', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'nmap-xml-summary', title: 'Nmap XML summary', agentId: 'nmap', image: min('nmap'), source: 'Built-in' },
	{ id: 'tshark-list-pcaps', title: 'List workspace pcaps', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'analyze_pcap', title: 'Analyze pcap', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'get_summary_stats', title: 'Pcap protocol stats', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'get_conversations', title: 'Pcap conversations', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'pcap-protocols', title: 'Pcap protocol hierarchy', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'pcap-endpoints', title: 'Pcap endpoints', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'pcap-dns', title: 'Pcap DNS', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'pcap-http', title: 'Pcap HTTP', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'pcap-follow-stream', title: 'Pcap follow stream', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'pcap-export-objects', title: 'Pcap export HTTP objects', agentId: 'tshark', image: min('tshark'), source: 'Built-in' },
	{ id: 'list_methods', title: 'List functions', agentId: 'ghidra', image: min('ghidra'), source: 'Built-in' },
	{ id: 'list_imports', title: 'List imports', agentId: 'ghidra', image: min('ghidra'), source: 'Built-in' },
	{ id: 'list_exports', title: 'List exports', agentId: 'ghidra', image: min('ghidra'), source: 'Built-in' },
	{ id: 'list_strings', title: 'List strings', agentId: 'ghidra', image: min('ghidra'), source: 'Built-in' },
	{ id: 'decompile_function', title: 'Decompile function', agentId: 'ghidra', image: min('ghidra'), source: 'Built-in' },
	{ id: 'list_xrefs', title: 'List xrefs', agentId: 'ghidra', image: min('ghidra'), source: 'Built-in' },
	{ id: 'ghidra-entry', title: 'Entry points', agentId: 'ghidra', image: min('ghidra'), source: 'Built-in' },
	{ id: 'r2_info', title: 'Binary info', agentId: 'radare', image: min('radare'), source: 'Built-in' },
	{ id: 'r2_functions', title: 'r2 functions', agentId: 'radare', image: min('radare'), source: 'Built-in' },
	{ id: 'r2_imports', title: 'r2 imports', agentId: 'radare', image: min('radare'), source: 'Built-in' },
	{ id: 'r2_strings', title: 'r2 strings', agentId: 'radare', image: min('radare'), source: 'Built-in' },
	{ id: 'r2_sections', title: 'r2 sections', agentId: 'radare', image: min('radare'), source: 'Built-in' },
	{ id: 'r2_libs', title: 'r2 libraries', agentId: 'radare', image: min('radare'), source: 'Built-in' },
	{ id: 'r2_disasm', title: 'r2 disasm', agentId: 'radare', image: min('radare'), source: 'Built-in' },
	{ id: 'binwalk_scan', title: 'Binwalk scan', agentId: 'binwalk', image: min('binwalk'), source: 'Built-in' },
	{ id: 'binwalk_entropy', title: 'Binwalk entropy', agentId: 'binwalk', image: min('binwalk'), source: 'Built-in' },
	{ id: 'binwalk_signature', title: 'Binwalk signatures', agentId: 'binwalk', image: min('binwalk'), source: 'Built-in' },
	{ id: 'binwalk_extract', title: 'Binwalk extract', agentId: 'binwalk', image: min('binwalk'), source: 'Built-in' },
	{ id: 'subfinder', title: 'Subfinder', agentId: 'subfinder', image: min('subfinder'), source: 'Built-in' },
	{ id: 'subfinder-silent', title: 'Subfinder silent', agentId: 'subfinder', image: min('subfinder'), source: 'Built-in' },
	{ id: 'subfinder-sources', title: 'Subfinder all sources', agentId: 'subfinder', image: min('subfinder'), source: 'Built-in' },
	{ id: 'dnsx', title: 'dnsx', agentId: 'dnsx', image: min('dnsx'), source: 'Built-in' },
	{ id: 'dnsx-a', title: 'dnsx A', agentId: 'dnsx', image: min('dnsx'), source: 'Built-in' },
	{ id: 'dnsx-cname', title: 'dnsx CNAME', agentId: 'dnsx', image: min('dnsx'), source: 'Built-in' },
	{ id: 'dns-resolve', title: 'DNS resolve', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-records', title: 'DNS records', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-ptr', title: 'DNS PTR', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-ns', title: 'DNS NS', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-mx', title: 'DNS MX', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-txt', title: 'DNS TXT', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-cname', title: 'DNS CNAME', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-soa', title: 'DNS SOA', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'dns-axfr-check', title: 'DNS AXFR check', agentId: 'dns', image: min('dns'), source: 'Built-in' },
	{ id: 'httpx', title: 'httpx', agentId: 'httpx', image: min('httpx'), source: 'Built-in' },
	{ id: 'httpx-title', title: 'httpx title', agentId: 'httpx', image: min('httpx'), source: 'Built-in' },
	{ id: 'httpx-tech', title: 'httpx tech', agentId: 'httpx', image: min('httpx'), source: 'Built-in' },
	{ id: 'naabu', title: 'naabu', agentId: 'naabu', image: min('naabu'), source: 'Built-in' },
	{ id: 'naabu-top-ports', title: 'naabu top ports', agentId: 'naabu', image: min('naabu'), source: 'Built-in' },
	{ id: 'katana', title: 'katana', agentId: 'katana', image: min('katana'), source: 'Built-in' },
	{ id: 'katana-depth', title: 'katana depth', agentId: 'katana', image: min('katana'), source: 'Built-in' },
	{ id: 'katana-js', title: 'katana JS', agentId: 'katana', image: min('katana'), source: 'Built-in' },
	{ id: 'nuclei', title: 'nuclei (info)', agentId: 'nuclei', image: min('nuclei'), source: 'Built-in' },
	{ id: 'nuclei-tech', title: 'nuclei tech', agentId: 'nuclei', image: min('nuclei'), source: 'Built-in' },
	{ id: 'nuclei-severity-info', title: 'nuclei info/low', agentId: 'nuclei', image: min('nuclei'), source: 'Built-in' },
	{ id: 'amass', title: 'Amass passive', agentId: 'amass', image: min('amass'), source: 'Built-in' },
	{ id: 'amass-passive', title: 'Amass passive enum', agentId: 'amass', image: min('amass'), source: 'Built-in' },
	{ id: 'ffuf_dir', title: 'ffuf dirs', agentId: 'ffuf', image: min('ffuf'), source: 'Built-in' },
	{ id: 'ffuf_vhost', title: 'ffuf vhost', agentId: 'ffuf', image: min('ffuf'), source: 'Built-in' },
	{ id: 'ffuf_extensions', title: 'ffuf extensions', agentId: 'ffuf', image: min('ffuf'), source: 'Built-in' },
	{ id: 'msf-search', title: 'MSF search', agentId: 'metasploit', image: min('metasploit'), source: 'Built-in' },
	{ id: 'msf-info', title: 'MSF module info', agentId: 'metasploit', image: min('metasploit'), source: 'Built-in' },
	{ id: 'msf-aux-scan', title: 'MSF auxiliary scan', agentId: 'metasploit', image: min('metasploit'), source: 'Built-in' },
	{ id: 'msf-http-version', title: 'MSF HTTP version', agentId: 'metasploit', image: min('metasploit'), source: 'Built-in' },
	{ id: 'msf-smb-version', title: 'MSF SMB version', agentId: 'metasploit', image: min('metasploit'), source: 'Built-in' },
	{ id: 'msf-ssh-version', title: 'MSF SSH version', agentId: 'metasploit', image: min('metasploit'), source: 'Built-in' },
	{ id: 'browser-search', title: 'Browser search', agentId: 'browser', image: min('browser'), source: 'Built-in' },
	{ id: 'browser-open', title: 'Browser open', agentId: 'browser', image: min('browser'), source: 'Built-in' },
	{ id: 'research-search', title: 'Research search', agentId: 'research', image: min('browser'), source: 'Built-in' },
	{ id: 'research-open', title: 'Research open', agentId: 'research', image: min('browser'), source: 'Built-in' },
	{ id: 'browser-snapshot', title: 'Browser snapshot', agentId: 'browser', image: min('browser'), source: 'Built-in' },
	{ id: 'browser-console', title: 'Browser console', agentId: 'browser', image: min('browser'), source: 'Built-in' },
	{ id: 'browser-network', title: 'Browser network', agentId: 'browser', image: min('browser'), source: 'Built-in' },
	{ id: 'browser-links', title: 'Browser links', agentId: 'browser', image: min('browser'), source: 'Built-in' },
	{ id: 'browser-close', title: 'Browser close', agentId: 'browser', image: min('browser'), source: 'Built-in' },
	{ id: 'scrapling-fetch', title: 'Scrapling fetch', agentId: 'scrapling', image: min('scrapling'), source: 'Built-in' },
	{ id: 'scrapling-text', title: 'Scrapling text', agentId: 'scrapling', image: min('scrapling'), source: 'Built-in' },
	{ id: 'scrapling-links', title: 'Scrapling links', agentId: 'scrapling', image: min('scrapling'), source: 'Built-in' },
	{ id: 'scrapling-select', title: 'Scrapling select', agentId: 'scrapling', image: min('scrapling'), source: 'Built-in' },
	{ id: 'scrapling-adaptive', title: 'Scrapling adaptive', agentId: 'scrapling', image: min('scrapling'), source: 'Built-in' },
	{ id: 'semgrep-list', title: 'Semgrep list', agentId: 'semgrep', image: min('semgrep'), source: 'Built-in' },
	{ id: 'semgrep-scan', title: 'Semgrep scan', agentId: 'semgrep', image: min('semgrep'), source: 'Built-in' },
	{ id: 'semgrep-owasp', title: 'Semgrep OWASP', agentId: 'semgrep', image: min('semgrep'), source: 'Built-in' },
	{ id: 'semgrep-path', title: 'Semgrep path', agentId: 'semgrep', image: min('semgrep'), source: 'Built-in' },
	{ id: 'juice-shop-status', title: 'Juice Shop status', agentId: 'juice-shop', image: 'bkimminich/juice-shop', source: 'Built-in' },
	{ id: 'knowledge-search', title: 'Knowledge search', agentId: 'runtime', image: '', source: 'Built-in' },
	{ id: 'knowledge-ingest', title: 'Knowledge ingest', agentId: 'runtime', image: '', source: 'Built-in' },
	{ id: 'start_service', title: 'Start service', agentId: 'runtime', image: '', source: 'Built-in' },
	{ id: 'stop_service', title: 'Stop service', agentId: 'runtime', image: '', source: 'Built-in' },
	{ id: 'restart_service', title: 'Restart service', agentId: 'runtime', image: '', source: 'Built-in' },
];

export const EXCLUDED_MCP_TOOLS = [
	{ id: 'msfvenom / exploit / payload / post', reason: 'Exploit capability denied. ADR 0005. Auxiliary scanners only.' },
	{ id: 'sqlmap_scan', reason: 'Exploitation. ADR 0003.' },
	{ id: 'extract_credentials', reason: 'Credential dump refused.' },
	{ id: 'scan-vulnerabilities', reason: 'NSE vuln/exploit path refused.' },
	{ id: 'scan-ports:syn|fin|xmas|null', reason: 'Stealth scan types refused.' },
	{ id: 'traceroute-connect', reason: 'Needs CAP_NET_RAW / raw sockets. Not wired.' },
	{ id: 'ghidra.eval / r2_command', reason: 'Arbitrary runtime exec refused.' },
	{ id: 'shell_command', reason: 'Host/container shell is not a model tool.' },
	{ id: 'podman machine / docker desktop', reason: 'Linux VM is human-only. Models start catalog images only.' },
	{ id: 'nuclei exploit/critical', reason: 'Exploit and high-severity templates refused.' },
	{ id: 'ffuf login/credential', reason: 'Password and credential spray refused.' },
	{ id: 'browser password/cookie harvest', reason: 'Password-field harvest and cookie theft refused.' },
	{ id: 'javascript: / XSS proof', reason: 'javascript: injection and XSS proofs are refused.' },
	{ id: 'drive-by download', reason: 'Drive-by downloads are refused.' },
	{ id: 'host Chrome / host Playwright', reason: 'Browser recon runs only in Podman Chromium. Host Chrome is not wired.' },
	{ id: 'host Wireshark / host dumpcap / live capture', reason: 'Packet analysis is contained tshark on workspace pcaps. Host GUI and live dumpcap are not wired.' },
	{ id: 'dns zone dump / AXFR transfer dump', reason: 'AXFR is a permit-check only. Zone dumps are not wired.' },
	{ id: 'scrapling python eval / exec', reason: 'Arbitrary Python in the scrapling image is refused. CSS/XPath only.' },
	{ id: 'captcha farm / WAF-attack / Turnstile solver', reason: 'CAPTCHA farms and WAF-attack kits are refused. Stealth is HTTP TLS impersonation of in-scope URLs only.' },
	{ id: 'credential stuffing / login spray', reason: 'Credential stuffing and login spray are refused.' },
	{ id: 'exploit / payload / PoC agents', reason: 'Engagement playbooks have no exploit phase. Validation uses SAST/recon evidence only.' },
	{ id: 'XSS / SQLi proof payloads', reason: 'Vuln-class agents detect only. Payloads and proofs are refused.' },
];
